# Note this file is used by the gasmeter and count pulses software!
[main]
# Max 10 characters for {room no} and {gas meter sn}
room no = B366
serial number = 98765432
# Default location for meter readings, do not change
meter reading file = etc/meterreading
# File used by kickstart
lock file = lockStatusCheck/gasmeter.lock
# Optional: file format - allowed file formats MJD, YYYY-MM, YYYY; default is YYYY-MM
#file format = YYYY-MM
# Optional: UPS parameters
# ups installed [true | 1] == present, [false | 0] == absent
ups installed = 1
# UPS software configuration has the name of the file with the 2 lines to
# display - the config file must be configured if the ups installed.
ups config file = /usr/local/etc/pi_ups.conf
# Optional: Time to show each set of rotating lines (in seconds), default is 10 seconds
# Values allowed: 5 seconds to 60 seconds.
rotate display = 10 

[gasmeters]
# one or more targets, if more than one target, an additional target
# called combined is automatically added, and a section called
# [combined] must be added by the user.
# If a single target is defined the name of the target MUST be 
# the same as the filename for [main][meter reading file] 
# otherwise the values will not be written to a location recognised by
# the gasmeter.py software.
targets = meterreading
#targets = meter1, meter2, meter3
meter reading path = etc/
# Lock file for the countpulses.py software
lock file = logs/countpulses.lock

[meterreading]
# input pin for pulsed; use BCM numbering (not physical pin numbers!)
input = 5
# volume per pulse in cubic meters
volume per pulse = 0.01
data path = data/
# file format can be one of YYYY (for a whole year's data in one file),
# or YYYY-MM (monthly files) or MJD (a day per file).
file format = YYYY-MM

[meter1]
input = 5
volume per pulse = 0.01
data path = data/meter1/
file format = MJD

[meter2]
input = 6
volume per pulse = 0.01
data path = data/meter2/
file format = MJD

[meter3]
input = 16
volume per pulse = 0.01
data path = data/meter3/
file format = MJD

[combined]
data path = data/
file format = MJD
