# Sample configuration file for waveshare_d_ups.py
#
#

[main]
# The user that owns the UPS application, configuration and data files
user = pi
# The lock file for the application
lock file = lockStatusCheck/waveshare_d_ups.lock
# Data must be logged at specified intervals (in seconds)
# Configured value must be an integer between 2 and 3600
log interval = 60

[data]
# Configure the path where the data must be stored
path = data/ups
# Configure the file extension for the data files
ext = ups

[status]
path = lockStatusCheck
file name = pi_ups.status

