#!/bin/bash

echo "Building intensity"
gcc -Wall intensity.c -o intensity -lwiringPi

echo "Copying countpulses, gasmeter and intensity to ${HOME}/bin/"
cp countpulses.py ${HOME}/bin/
cp gasmeter.py ${HOME}/bin/
cp intensity ${HOME}/bin/

echo "Copying broadcast and rcvmsg to ${HOME}/bin"
cp broadcast.py ${HOME}/bin/
cp recvmsg.py ${HOME}/bin/
